apiVersion: v1
kind: Pod
metadata:
    name: pod-nginx
    labels:
      app: nginx-pod 
spec:
    containers:
        - name: container-nginx
          image: nginx_soap_script:latest
          imagePullPolicy: Never #to run images on local disk
          ports:
            - containerPort: 80