apiVersion: v1
kind: Service
metadata:
    name: svc-ejb-demo-k8s
spec:
    type: NodePort
    selector:
      app: ejb-demo-k8s
    ports:
      - port: 8080
        nodePort: 30000  
status:
  loadBalancer: {} 